name: Parallel Jobs with Strategy Matrix

on:
  push:
    branches:
      - main
  workflow_dispatch: # This allows manual triggering of the workflow

jobs:
  build:
    name: Build Job
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15]

    steps:
      - name: Print OS
        run: echo "Operating System: ${{ matrix.os }}"

