name: Docker Publish for Github

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering from the GitHub web interface or API

jobs:
  publish:
    name: Build and Publish Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Publish Docker image
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.repository_owner }} --password-stdin
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64 --push -t docker.pkg.github.com/${{ github.repository }}/${{ github.repository }}:latest .

